
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  taleweaver_frontend:
    container_name: talweaver_frontend
    image: ghcr.io/utsc-cscc09-programming-on-the-web/taleweaver_frontend
    ports:
      - "80:80"
    depends_on:
      - taleweaver_backend
    restart: always
  taleweaver_backend:
    container_name: taleweaver_backend
    build: ./backend/ 
    image: ghcr.io/utsc-cscc09-programming-on-the-web/taleweaver_backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=taleweaver_db
      - REDIS_HOST=taleweaver_redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_TEXT_TO_SPEECH_API_KEY=${GOOGLE_TEXT_TO_SPEECH_API_KEY}
    depends_on:
      - taleweaver_db
      - taleweaver_redis
    restart: always

  taleweaver_worker:
    container_name: taleweaver_worker
    image: ghcr.io/utsc-cscc09-programming-on-the-web/taleweaver_backend
    command: npm run worker
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=taleweaver_db
      - REDIS_HOST=taleweaver_redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_TEXT_TO_SPEECH_API_KEY=${GOOGLE_TEXT_TO_SPEECH_API_KEY}
    depends_on:
      - taleweaver_db
      - taleweaver_redis
    restart: always

  taleweaver_db:
    container_name: taleweaver_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
    volumes:
      - taleweaver_db_data:/var/lib/postgresql/data
  
  taleweaver_redis:
    container_name: taleweaver_redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  taleweaver_db_data: {}
