
services:
  # TODO: Add frontend
  taleweaver_backend:
    container_name: taleweaver_backend
    build: ./backend/ 
    image: taleweaver/backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
      - POSTGRES_HOST=taleweaver_db
    depends_on:
      - taleweaver_db
    restart: always

  taleweaver_db:
    container_name: taleweaver_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
    volumes:
      - taleweaver_db_data:/var/lib/postgresql/data
  
  taleweaver_redis:
    container_name: taleweaver_redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  taleweaver_db_data: {}
